--Câu 27--
SELECT COUNT(*) AS SLGV, SUM(LUONG) AS TONGLUONG
FROM GIAOVIEN
--Câu 28--
SELECT BM.MABM, COUNT(*) AS SLGV, AVG(GV.LUONG) AS LUONGTRUNGBINH
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MABM=BM.MABM
GROUP BY BM.MABM
--Câu 29--
SELECT CD.TENCD, COUNT(*) AS SLDT
FROM DETAI DT, CHUDE CD
WHERE DT.MACD=CD.MACD
GROUP BY CD.MACD, CD.TENCD
--Câu 30--
SELECT GV.HOTEN, COUNT(DISTINCT TGDT.MADT) AS SLDT
FROM GIAOVIEN GV, THAMGIADT TGDT
WHERE GV.MAGV=TGDT.MAGV
GROUP BY GV.MAGV, GV.HOTEN	
--Câu 31--
SELECT GV.HOTEN, COUNT(DISTINCT DT.MADT) AS SLDTCN
FROM GIAOVIEN GV, DETAI DT
WHERE GV.MAGV=DT.GVCNDT
GROUP BY GV.MAGV, GV.HOTEN
--Câu 32--
SELECT GV.HOTEN, COUNT(*) AS SOLUONGNT
FROM GIAOVIEN GV, NGUOITHAN NT
WHERE NT.MAGV=GV.MAGV
GROUP BY GV.MAGV, GV.HOTEN
--Câu 33--
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TGDT
WHERE GV.MAGV=TGDT.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TGDT.MADT)>=3
--Câu 34--
SELECT COUNT(*) AS SLGV
FROM GIAOVIEN GV, THAMGIADT TGDT, DETAI DT
WHERE GV.MAGV=TGDT.MAGV
AND DT.MADT=TGDT.MADT
AND DT.TENDT=N'Ứng dụng hóa học xanh'
GROUP BY GV.MAGV